PROJECT = "what2eat"
TREATMENT = "treatment_a"  # or "treatment_b" or "treatment_c"
REF_PATH = f"ref/{PROJECT}"
DOC_PATH = f"doc/{PROJECT}"
GENERATED_PATH = f"generated/{PROJECT}/{TREATMENT}"
PROMPT_PATH = f"prompts/{PROJECT}/{TREATMENT}"
